USE sakila;


#List the number of films per category.

SELECT name, COUNT(film_id)
FROM category
INNER JOIN film_category
USING (category_id)
GROUP BY name
ORDER BY COUNT(film_id) DESC;

#Retrieve the store ID, city, and country for each store.

SELECT store_id, city.city, country.country
FROM store
INNER JOIN address
USING (address_id)
INNER JOIN city
USING (city_id)
INNER JOIN country
USING (country_id);

#Calculate the total revenue generated by each store in dollars.

SELECT store_id, CONCAT( "$", FORMAT(SUM(amount),2))
FROM store
INNER JOIN customer
USING (store_id)
INNER JOIN payment
USING (customer_id)
GROUP BY store_id;

#Determine the average running time of films for each category.

SELECT name , FORMAT(AVG(length),2)
FROM category
INNER JOIN film_category
USING (category_id)
INNER JOIN film
USING (film_id)
GROUP BY name;


#Bonus:

# Identify the film categories with the longest average running time.

SELECT name, ROUND(AVG(length),2)
FROM category
INNER JOIN film_category
USING (category_id)
INNER JOIN film
USING (film_id)
GROUP BY name
ORDER BY AVG(length) DESC;

# Display the top 10 most frequently rented movies in descending order.

SELECT title, COUNT(*)
FROM rental
INNER JOIN inventory
USING (inventory_id)
INNER JOIN film
USING (film_id)
GROUP BY title
ORDER BY COUNT(*) DESC
LIMIT 10;

# Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT store_id , title
FROM store
INNER JOIN inventory
USING (store_id)
INNER JOIN film
USING (film_id)
WHERE title = "Academy Dinosaur" and store_id =1;

# Provide a list of all distinct film titles, along with their availability status in the inventory. 
# Include a column indicating whether each title is 'Available' or 'NOT available.' 
# Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."

SELECT * FROM inventory;

SELECT title
CASE
	WHEN title IF NULL THEN "Not available"
    ELSE "Available"
END AS inventory_status
FROM film
LEFT JOIN inventory
USING (film_id);


